spring.application.name=devtest

# Server config
server.port=8800
env.app=DEV
#${ENV_APP}

# Frankfurter API
frankfurter.base-url=https://api.frankfurter.dev

# Logging (optional but useful)
logging.level.org.springframework.web=INFO
logging.level.reactor.netty.http.client=DEBUG
logging.level.org.springframework.web.reactive.function.client=DEBUG

# Timeout tuning (optional)
spring.codec.max-in-memory-size=5MB